[project]
name = "textbook-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.124.4",
    "ipykernel>=7.1.0",
    "uvicorn>=0.38.0",
    "python-multipart>=0.0.6"  # Add this for file uploads
]
